version: '3.4'
services:
  efb:
    build:
      context: .
      dockerfile: Dockerfile
    #ports:
    #  - "127.0.0.1:5005:5005"
    network_mode: "host"
    volumes:
      - /mnt/hd1/101/EFB:/root/.ehforwarderbot:rw
    restart: always
